<section class="main_section-2">
    <div class="container">
        <article class="main_section-2_article-1">
            <img src="img/img_coach.jpg" alt="Photo d'un prof de sport">
                <section class="main_section-2_article-1_teacher">
                
                    <h2>Partager votre passion</h2>
                    <p>Vous etes un amateur de course ou un grand athlete, lancez-vous et accompagnez des personnes qui veulent reprendre une activité physique !</p>
                    <a class="normal-link t-a-center uppercase" href="#">3, 2, 1 ... c'est parti</a>

                </section>    
        </article>
    </div>

    <div class="clear"></div>
    <div class="container">
        <article class="main_section-2_article-2">
            <img src="img/img_student.jpg" alt="Photo d'un eleve de sport">
                <section class="main_section-2_article-2_student">
                
                    <h2>Reprenez votre vie en main</h2>
                    <p>C'est le moment de sauter cette barriere et de vous remettre au sport. Grace a nos 1500 particuliers, prenez un cours de sport a domicile ou en pleine nature</p>
                    <a class="normal-link t-a-center uppercase" href="#">3, 2, 1 ... c'est parti</a>

                </section>      
        </article>
    </div>
    <div class="clear"></div>

</section>
<div class="container">
    <section class="main_section-3" id="about">
        <article class="main_section-3_article-1">
            <div class="separateur">
                <h2 class="t-a-center">Je veux faire du sport !</h2>
                <h1 class="uppercase t-a-center">give you a chance est la pour vous</h1>
                <p>Avec Give You A Chance, accordez vous un moment pour vous sans parcourir la capital a trouver la meilleure salle de sport. Une equipe de 1500 particulier et professionels sont la pour vous.</p>
                <p>De chez vous, en quelques click, choisissez un prof particulier pour une séance de coaching personalisé.</p>
                <p>Vous avez toujours revé de vous initier au tenis ? Il y aura forcement un prof pour vous.</p>
            </div>
            <a class="uppercase normal-link t-a-center" href="subscribe.php">inscrivez-vous</a>

        </article>
        <article class="main_section-3_article-2">

            <div class="separateur">
                <h2 class="t-a-center">Je veux donner un cours</h2>
                <h1 class="uppercase t-a-center">faite profiter vos connaissances</h1>
                <p>Vous aimez partager votre passion pour le sport, Give You A Chance vous permet d'arrondir vos fins de mois tout en faisant ce que vous aimz</p>
                <p>Que vous soyez profesionnel du jogging ou joueur de Squach du dimanche il y aura forcement quelq'un pour partager avec vous cette discipline.</p>
            </div>
            <a class="uppercase normal-link t-a-center" href="subscribe.php">inscrivez-vous</a>

        </article>
    </section>
</div>

