<div class="container">
    <form class="main_form_login" action="login.php" method="POST">

        <fieldset>
            <legend class="main_form_subscribe_legend uppercase">connexion</legend>
            
            <div class="bloc_connexion_login">
                <div class="bloc_connexion_mail">
                    <label>Saisissez votre mail</label>
                    <input type="text" name="mail" placeholder="@Mail">
                </div>
                
                <div class="bloc_connexion_psw">
                    <label>Mot de passe</label>
                    <input type="password" name="password" placeholder="Mot de passe">
                </div>
            

                <button class="uppercase" type="submit"><p>connexion</p></button>
            </div>
        </fieldset>
    </form>
</div>