<div class="container">
    <div class="login-space bg-c-black">
        <div class="register-space_form">
            <form action="<?= $requestUrl ?>/user/login" method="POST">
                <div class="inputGroup">
                    <label>Votre adresse mail</label>
                    <input id="mail" name="mail" type="mail">
                </div>
                <div class="inputgroup">
                    <label>Saisissez votre mot de passe</label>
                    <input id="password" name="password" type="password">
                </div>
                <button class="uppercase" type="submit">valider</button>
            </form>
        </div>
    </div>
</div>