<section class="home_section">
    <article class="home_section_article-teacher">
        <div class="home_section_article-teacher_img">
            <img src="" alt="">
        </div>
        <div class="home_section_article-teacher_about">
            
        </div>
    </article>
    <article class="home_section_article-student">
        <div class="home_section_article-student_img">
            <img src="" alt="">
        </div>
        <div class="home_section_article-student_about">
            
        </div>
    </article>
</section>