<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home.css">
<div class="container">
    <section class="home_section fl-jc-b">
        <article class="home_section_article-teacher">
            <div class="home_section_article-teacher_img">
                <h2 class="t-a-center ud-p-50">Je veux prendre un cours</h2>
                <img src="<?= $wwwUrl ?>/images/index/teacher.jpg" alt="image de coache sportif">
            </div>
            <div class="home_section_article-teacher_about">
                
            </div>
        </article>
        <article class="home_section_article-student">
            <div class="home_section_article-student_img">
                <h2 class="t-a-center ud-p-50">Je veux donner un cours</h2>
                <img src="<?= $wwwUrl ?>/images/index/coach.jpg" alt="">
            </div>
            <div class="home_section_article-student_about">
                
            </div>
        </article>
    </section>
</div>