
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home.css">

    <div class="layout_header_bloc-info container">
        <h1 class="uppercase t-a-center bold ud-p-20">accordez-vous une chance</h1>
        <p class="uppercase t-a-center bold ud-p-20">avec give you a chance, donnez ou recevez un cours de sport entre particulier a domicile ou proche de chez vous.</p>
        <a class="uppercase normal-link t-a-center ud-p-20 bg-c-black c-white" href="#about">en savoir plus</a>
    </div>
</header>

<div class="container ">
    <section id="about" class="home_section fl-jc-b">
        <article class="home_section_article-teacher">
            <div class="home_section_article-teacher_img touch">
                <h2 class="t-a-center ud-p-20 uppercase">je veux donner un cours</h2>
                <img class="img_about" src="<?= $wwwUrl ?>/images/index/teacher.jpg" alt="image de coache sportif">
                <div class="home_section_article-teacher_about t-a-center">
                    <h3>Vous aussi devenez coach sportif et transmettez votre passion</h3>
                    <a class="uppercase normal-link t-a-center p-20 bg-c-black c-white" href="<?= $requestUrl ?>/about/teacher">laissez vous guidez</a>
                </div>
            </div>
            
        </article>
        <article class="home_section_article-student">
            <div class="home_section_article-student_img touch">
                <h2 class="t-a-center ud-p-20 uppercase">je veux prendre un cours</h2>
                <img class="img_about" src="<?= $wwwUrl ?>/images/index/coach.jpg" alt="">
                <div class="home_section_article-student_about t-a-center">
                    <h3>Sautez le pas et devenez Peter McKAloway</h3>
                    <a class="uppercase normal-link t-a-center p-20 bg-c-black c-white" href="<?= $requestUrl ?>/about/student">laissez vous guidez</a>
                </div>
            </div>
        </article>
    </section>
</div>
