<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Give you a Chance ! // Acceuil</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- Feuilles de styles d'auto-class -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/auto-class.css">

    <!-- Feuilles de styles -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/layout.css">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
    <body>

        <header id="header" class="layout_header">
            <nav class="layout_header_bloc-nav fl-jc-b ud-p-20 bg-c-black">
                <div class="layout_header_bloc_left">
                    <ul class="layout_header_bloc_left_list">
                        <li><a class=" normal-list normal-link p-20" href="<?= $requestUrl ?>/">Give You A Chance</a></li>

                        <li><a class ="uppercase normal-list normal-link p-20" href="<?= $requestUrl ?>/shop">boutique</a></li>
                        <li><a class ="uppercase normal-list normal-link p-20" href="">contact</a></li>
                    </ul>
                </div>

                <div class="layout_header_bloc_right">
                    <ul class="layout_header_bloc_right_list">


                        <?php if($_SESSION == false): ?>
                            <li><a class ="uppercase normal-list normal-link p-20" href="<?= $requestUrl ?>/user/login">connexion</a></li>
                            <li><a class ="uppercase normal-list normal-link p-20" href="<?= $requestUrl ?>/user/register">inscription</a></li>
                        <?php endif ?>
                        <?php if($_SESSION == true): ?>
                            <li><a class ="uppercase normal-list normal-link p-20" href="<?= $requestUrl ?>/user/destroy">deconnexion</a></li>
                        <?php endif ?>
                    </ul>
                </div>
            </nav>

        <main>
            <?php include $this->viewData['template'] ?>
        </main>

        <!-- Pied de page commun -->
        <footer>
            
        </footer>

        <!-- Code principal JavaScript de l'application -->
        <script src="<?= $wwwUrl ?>/js/main.js"></script>

    </body>
</html>