<link rel="stylesheet" href="<?= $wwwUrl ?>/css/register.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/radioregister.css">

<div class="container">
    <div class="register-space bg-c-black">

        <div class="register-space_form fl-jc-b">            
            <div class="left">
                <img src="<?= $wwwUrl ?>/images/form/bodybuild.png" alt="">
                <a class="uppercase normal-link c-white t-a-center ud-p-20" href="">connexion</a>
            </div>
            <form class="register_form p-20" action="<?= $requestUrl ?>/user/register" method="POST">
                <div class="right bg-c-white">
                    <div id="first_fieldset" class="form_min-height p-20">
                        <fieldset>  
                            <legend class="uppercase">étape 1</legend>                  
                            <div class="register-space_form_step-one form p-50">
                                <label>Je veux :</label>
                                <div class="radio_register">
                                    <div class="inputGroup">
                                        <input id="radio1" name="radio" type="radio" value="student"/>
                                        <label class="uppercase" for="radio1">faire du sport</label>
                                    </div>
                                    <div class="inputGroup">
                                        <input id="radio2" name="radio" type="radio" value="teacher"/>
                                        <label class="uppercase" for="radio2">donner un cours</label>
                                    </div>
                                </div>
                                <div class="inputmail">
                                    <label>Votre adresse mail :</label>
                                    <input id="mail" name="mail" type="mail">
                                </div>
                                <a id="subscribe_do-move" class="uppercase normal-link t-a-center p-10 bg-c-black c-white" href="">suivant</a>
                            </div>
                            
                        </fieldset>
                    </div>
                    <div id="second_fieldset" class="form_min-height p-20 d-show"> 
                        <fieldset>  
                            <legend class="uppercase">étape 2</legend>               
                            <div class="register-space_form_step-two form bg-c-white">
                                <div class="inputlabel">                    
                                    <label>Prénom :</label>
                                    <input type="text" name="firstName" id="firstName">
                                </div>
                                <div class="inputlabel"> 
                                    <label>Nom :</label>
                                    <input type="text" name="lastName" id="lastName">
                                <div class="inputlabel">
                                    <label>Choisissez un mot de passe :</label>
                                    <input id="password" name="password" type="password">
                                </div>
                                
                                <button class="uppercase p-10 bg-c-black c-white" type="submit">valider</button>
                            </div>
                            <a class="normal-link" id="come_back" href=""><i class="fas fa-arrow-left"></i></a>
                        </fieldset>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

<script src="<?= $wwwUrl ?>/js/RegisterAnimation.js"></script>
