<link rel="stylesheet" href="<?= $wwwUrl ?>/css/register.css">

<div class="container">
    <div class="register-space bg-c-black">
        <div class="register-space_form">
            <form action="<?= $requestUrl ?>/application/controller/user/register">
                <div class="left">
                    <img src="<?= $wwwUrl ?>/images/form/bodybuild.png" alt="">
                </div>
                <div class="right">
                    <div class="form_min-height">                    
                        <div class="register-space_form_step-one bg-c-white">
                        </div>
                    </div>
                    <div class="form_min-height">                
                        <div class="register-space_form_step-two d-show bg-c-white">                    
                        </div>
                    </div>
                    <div class="form_min-height">
                        <div class="register-space_form_step-three d-show bg-c-white">                    
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>