<link rel="stylesheet" href="<?= $wwwUrl ?>/css/TeacherAbout.css">

<div class="container">
    <section class="teacher-about_section">
        <h1 class="t-a-center uppercase ud-p-50">partagez vos competences</h1>

        <div class="para1 ud-p-20">
            <div class="text1 p-20">
                <h2 class="ud-p-10">Lorem ipsum dolor sit amet.</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, enim! Quisquam consectetur repudiandae error inventore voluptatem maxime provident harum sed, necessitatibus quae nemo culpa exercitationem dolores quod officia itaque accusantium reprehenderit explicabo natus minima alias earum. Consectetur, recusandae! Quod repudiandae similique quidem non soluta atque nobis suscipit iste asperiores harum. Delectus tenetur exercitationem velit totam amet, autem deleniti tempora eveniet quibusdam dicta sequi. Illum quod veniam saepe ipsa magnam, aperiam vero tempore adipisci est excepturi animi dolores consequuntur. Distinctio quasi rem mollitia fugiat ad excepturi praesentium cupiditate in obcaecati at molestiae asperiores nihil porro, recusandae quisquam ut aliquid hic commodi.</p>
            </div>
            <div class="img1 p-20">
                <img src="<?= $wwwUrl ?>/images/teacher/1.jpg" alt="">
            </div>
        </div>

        <div class="clear"></div>

        <div class="para2 ud-p-20">
            <div class="text2 p-20">
                <h2 class="ud-p-10">Lorem ipsum dolor sit amet.</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, enim! Quisquam consectetur repudiandae error inventore voluptatem maxime provident harum sed, necessitatibus quae nemo culpa exercitationem dolores quod officia itaque accusantium reprehenderit explicabo natus minima alias earum. Consectetur, recusandae! Quod repudiandae similique quidem non soluta atque nobis suscipit iste asperiores harum. Delectus tenetur exercitationem velit totam amet, autem deleniti tempora eveniet quibusdam dicta sequi. Illum quod veniam saepe ipsa magnam, aperiam vero tempore adipisci est excepturi animi dolores consequuntur. Distinctio quasi rem mollitia fugiat ad excepturi praesentium cupiditate in obcaecati at molestiae asperiores nihil porro, recusandae quisquam ut aliquid hic commodi.</p>
            </div>
            <div class="img2 p-20">
                <img src="<?= $wwwUrl ?>/images/teacher/2.jpg" alt="">
            </div>
        </div>
    </section>
</div>